### ISSUE TITLE
hotfix/ add .git to URL

### ISSUE THREAD

**Issue by rogerpearce** [LLNL/ygm#148]
@steiltre could you add ".git" to the URL and push the commit to both master and develop?

https://github.com/LLNL/ygm/blob/ca3a82eaf614beb5291705670c8f0940fd61e9c8/CMakeLists.txt#L75

**Comment by steiltre** [comment]
Taken care of in [PR #149](https://github.com/LLNL/ygm/pull/149) and [PR #150](https://github.com/LLNL/ygm/pull/150).
