### ISSUE TITLE
Apache Arrow CI Test

### ISSUE THREAD

**Issue by KIwabuchi** [LLNL/ygm#179]
Hi,

I'm wondering if Arrow and Parquet are tested during CI.

It looks like the CMake file asks for Arrow v8, v9, or v10:
https://github.com/LLNL/ygm/blob/1e2297ac37389b6f5a396307547e7246580e1529/CMakeLists.txt#L137-L142
On the other hand, the CI test YAML file downloads the latest version:
https://github.com/LLNL/ygm/blob/1e2297ac37389b6f5a396307547e7246580e1529/.github/workflows/ci-test.yaml#L41

I'm not sure which version the command above downloads, but the latest version I can download manually is 13 now (surprisingly, they did a few major version releases within one year...).
I can't see CI test log files as I don't have permission. Could someone check that for me? 

Keita

**Comment by steiltre** [comment]
Thanks for catching this. Arrow 13.0 is being installed and not found by CMake, so the Arrow CI is not running. I'll fix this to specifically download Arrow 13.0 and add it into the CMakeLists.txt.

Are there any good ways to handle versioning of dependencies like this? I see CMake supports version ranges starting in CMake 3.19 which would make it easier to incorporate new versions of Arrow, but there doesn't appear to be a good way of asking for "Arrow>=8.0".

**Comment by KIwabuchi** [comment]
Thanks for quickly checking it.

That's a good question. I'm also not sure what is a good way to do that.
If `find_package(Arrow 8.0)` does not accept `Arrow > 9.0`, no compatibility guarantee exists between 8.0 and >=9.0.
So, I think we need to manually update and test our CMake and CI Test configurations when they release new major versions.
Fortunately, we will actively keep developing YGM and using Arrow Parquet for a while.
I hope their major version release speed gets slowed down relatively soon...

**Comment by steiltre** [comment]
Added a check for Apache Arrow 13.0 in [PR 180](https://github.com/LLNL/ygm/pull/180). I also configured to have CMake throw an error in CI jobs when  Arrow isn't found. This should make it more obvious to use when Apache updates the version of Arrow rather than silently not running our Arrow-dependent tests.

**Comment by KIwabuchi** [comment]
#180 looks good to me!
